### ISSUE TITLE
Préparation de l'environnement

### ISSUE THREAD

**Issue by elberdaoui** [elberdaoui/C2N3_C3N3#1]
- [x] `git clone /lien Repository/` ou `Fork`

- [x] `npm install /pakages/`

- [x] `Watching` `concatenation` `Préfixage` avec `NPM Scripts`

- [x] `Compression` du `css` et `Javascript` avec `NPM Scripts`

**Comment by imanegannaoui** [comment]
Très bon travail! tu peux ajouter Milestone pour faire le suivi avec le temps
